@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxIiwiZW1haWwiOiJjdXN0b21lckBpZGV2LmNvbSIsImlhdCI6MTY4MTQ4MzA2OCwiZXhwIjoxNjgxNDgzMTg4fQ.G1Z1HNFhCqTnFLTRoQBPl77A_dx5J9aE6v20VPtkXUc
@hostname = http://localhost:4000
@contentType = application/json


GET {{hostname}}/api/v1/profile
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

