@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxIiwiZW1haWwiOiJkZXZAaWRldi5jb20iLCJpYXQiOjE2ODE3MDA5MzksImV4cCI6MTY4MTcwMTA1OX0.oRwMwnARC--WOiId1QOHFbYMs-M5pO5777a9WyvsOzw
@hostname = http://localhost:4000
@contentType = application/json


GET {{hostname}}/api/v1/profile
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

