@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxIiwiZW1haWwiOiJkZXZAaWRldi5jb20iLCJpYXQiOjE2ODE0NDk2MjgsImV4cCI6MTY4MTQ0OTc0OH0.Atfp3ABzvF5aG-RzFjhudcbLtHFp-vyF4Ga7FqF4eoo
@hostname = http://localhost:4000
@contentType = application/json


GET {{hostname}}/api/v1/profile
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

